# Site settings
title: "NYC Planning Labs: Modern GovTech"
description: "NYC Planning Labs builds open, impactful technology tools for NYC's Urban Planners."
baseurl: "" # the subpath of your site, e.g. /blog
permalink: pretty
url: "https://planninglabs.nyc" # the base hostname & protocol for your sites
localhost: "localhost:4000"
env: "production"
logo:
tag_dir: tags
github_repo: https://github.com/NYCPlanning/labs-planninglabs.nyc/blob/master
future: true

related_posts: 3

# Google services
google_analytics: UA-84250233-4

analytics:
  google:
    code: '' # Change this to your GSA analytics code
  dap:
    agency: DCP    # Change this to your agency
    subagency: Labs # Change this to your agency

# blog archive at /blog
paginate: 5
paginate_path: "blog/page/:num"

jekyll-archives:
  enabled:
    - 'tags'
  layout: tag-results
  permalinks:
    tag: '/tags/:name/'

collections:
  about:
    output: true
    permalink: /:path/
  join:
    output: true
    permalink: /join/:path/
  authors:
    output: true
    permalink: /author/:name/
  press:
    output: true
    permalink: /press/:name/
  projects:
    output: true
    permalink: /what-we-deliver/:path/
  contact:
    output: false
    permalink: /contact/:path/
  styleguide:
    output: true
    permalink: /styleguide/:path/

defaults:
 -
  scope:
    type: "posts" # an empty string here means all files in the project
  values:
    layout: post
 -
  scope:
    path: "pages"
  values:
    layout: primary
 -
  scope:
    path: "_authors"
  values:
    layout: default-profile
 -
  scope:
    path: "_contact"
  values:
    layout: primary
    # include_subnav: true
    subnav_anchor: /contact/
 -
  scope:
    path: "_about"
  values:
    layout: primary
    include_subnav: true
    subnav_anchor: /about/
 -
  scope:
    path: "_projects"
  values:
    layout: project-page
 -
  scope:
    path: "_styleguide"
  values:
    layout: styleguide
    include_subnav: true

frontmatter_tests:
  path: "tests/schema"

footer:
  image:
  email:
  twitter:
    - nycplanninglabs
  text: This site was cloned from 18F.gsa.gov</a>. # Change to a tag line for your agency

# Build settings
markdown: kramdown
highlighter: rouge

exclude:
- .about.yml
- .cfignore
- .codeclimate.yml
- .gitignore
- .gitmodules
- .hound.yml
- 404.html
- api-endpoints
- bin
- build
- circle.yml
- config_blog.rb
- CONTRIBUTING.md
- docker-compose.yml
- docker_entrypoint.rb
- Dockerfile
- examples/
- Gemfile*
- ISSUE_TEMPLATE.md
- killport
- LICENSE.md
- node_modules
- package.json
- pages/our-work.html
- PULL_REQUEST_TEMPLATE.md
- README.md
- spec/
- system-security-plan.yml
- tests/
- tests/schema/tags.yml
- tmp/
- vendor

# jekyll plugins
gems:
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

# Configuration for jekyll_pages_api_search plugin gem.
jekyll_pages_api_search:
  # Uncomment this to speed up site generation while developing.
  #skip_index: true

  # Each member of `index_fields` should correspond to a field generated by
  # the jekyll_pages_api. It can hold an optional `boost` member as a signal
  # to Lunr.js to weight the field more highly (default is 1).
  index_fields:
    title:
      boost: 10
    tags:
      boost: 10
    url:
      boost: 5
    body:
